name: Test GitHub-Hosted Runners (Temporary)

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
      environment:
        description: 'Target environment'
        required: true
        default: 'stage'
        type: choice
        options:
        - stage
        - prod

jobs:
  test-workflow-logic:
    runs-on: ubuntu-latest  # Using GitHub-hosted runners temporarily
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test workflow logic
      run: |
        echo "=== TESTING WORKFLOW LOGIC ==="
        echo "This tests if our workflow structure works correctly"
        echo "Using GitHub-hosted runners temporarily"
        echo ""
        echo "Action: ${{ github.event.inputs.terraform_action }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Runner: $(hostname)"
        echo "Working directory: $(pwd)"
        
    - name: Simulate Terraform Plan
      run: |
        echo "=== SIMULATED TERRAFORM PLAN ==="
        echo "Would run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo ""
        echo "Plan would target:"
        echo "- CloudSQL rd database (${{ github.event.inputs.environment }})"
        echo "- Database users and permissions"
        echo ""
        echo "Sample output:"
        echo "Plan: 3 to add, 1 to change, 0 to destroy"
        
    - name: Simulate Terraform Apply
      if: github.event.inputs.terraform_action == 'apply'
      run: |
        echo "=== SIMULATED TERRAFORM APPLY ==="
        echo "Would run: terraform apply -auto-approve"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Apply complete! Resources: 3 added, 1 changed, 0 destroyed"
        
    - name: Workflow Test Summary
      run: |
        echo "=== WORKFLOW LOGIC TEST COMPLETED ==="
        echo "Status: Workflow structure working"
        echo "Input parameters: Working"
        echo "Conditional logic: Working"
        echo "Action: ${{ github.event.inputs.terraform_action }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo ""
        echo "Next: Switch back to self-hosted runners once ARC issue is resolved"
