name: Test ARC Runners

on:
  workflow_dispatch:

jobs:
  test-terraform-runner:
    name: Test Terraform Runner  
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Prove Terraform Runner Works
      shell: bash
      run: |
        echo "SUCCESS: Terraform runner is working!"
        echo "Date: $(date)"
        echo "Hostname: $(hostname)"
        echo "User: $(whoami)"
        echo "Groups: $(groups)"
        echo "Kubernetes pod name: $HOSTNAME"
        
    - name: Test file permissions
      shell: bash
      run: |
        echo "Testing file permissions (permission fix verification)..."
        mkdir -p ./test-dir && echo "SUCCESS: Can create directory" || echo "ERROR: Cannot create directory"
        touch ./test-file && echo "SUCCESS: Can create file" || echo "ERROR: Cannot create file"
        echo "test content" > ./test-file && echo "SUCCESS: Can write file" || echo "ERROR: Cannot write file"
        mkdir -p /tmp/tool-test && echo "SUCCESS: Can create tool directories" || echo "ERROR: Cannot create tool directories"
        echo "This proves the security context fix is working!"
