name: Test Terraform Runners

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-runners:
    runs-on: [self-hosted, terraform-runners]
    
    steps:
    - name: Hello from ARC
      run: |
        echo "Hello from ARC terraform-runners!"
        echo "Date: $(date)"
        echo "Runner hostname: $(hostname)"
        echo "Working directory: $(pwd)"
        echo "User: $(whoami)"
        
    - name: Runner Environment Info
      run: |
        echo "=== Runner Environment ==="
        echo "OS: $(uname -a)"
        echo "CPU cores: $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 'Unknown')"
        echo "Memory info:"
        free -h 2>/dev/null || vm_stat | head -5 2>/dev/null || echo "Memory info not available"
        
    - name: Test Complete
      run: |
        echo "ARC terraform-runners test completed successfully!"
        echo "Scale set is working correctly!"
